### PR TITLE
"Discord" theme

### PR DESCRIPTION
**Pull request by no1crate**
It uses Discords colors for it!

### CODE REVIEW

**Review by no1crate — COMMENTED** [review]
First version, ignores accessibility. Uses discord colors.

**Comment by donut28** [comment]
Make sure you offset the colors by one or Discord might make your theme **_not exist_** due to copyright!

Danger zone:
> `#445dff`

Safe from discord ruining your work:
> `#445dfe`

Otherwise, looking good.

**Comment by no1crate** [comment]
> Make sure you offset the colors by one or Discord might make your theme **_not exist_** due to possible copyright on the colors!
> 
> Danger zone:
> 
> > `#445dff`
> 
> Safe from discord ruining your work:
> 
> > `#445dfe`
> 
> Otherwise, looking good.

Thanks! Will do that.

**Comment by no1crate** [comment]
> 445dfe

That colors are from the basic code. I didn't add them!

**Comment by donut28** [comment]
> > 445dfe
> 
> That colors are from the basic code. I didn't add them!

If your colours are slightly different than discord, then it should be fine.

**Comment by no1crate** [comment]
> > > 445dfe
> > 
> > 
> > That colors are from the basic code. I didn't add them!
> 
> If your colours are slightly different than discord, then it should be fine.

For example, a E instead of a F?

**Comment by no1crate** [comment]
Done!

**Review by no1crate — COMMENTED** [review]
Done! Waiting for merge!

**Review by donut28 — APPROVED** [review]
👍

**Review by donut28 — APPROVED** [review]
Works good 👍

**Pull request merged**
