### PR TITLE
Adding optimized "Discord" version. (I think all the things are ok)

### PR DESCRIPTION
**Pull request by no1crate**
Adding it because I think it's good

### CODE REVIEW

**Comment by no1crate** [comment]
(Sorry for the 8000 things that appear before this pr)

**Comment by thekifake** [comment]
i dont think colours are copyrighted

**Comment by no1crate** [comment]
> i dont think colours are copyrighted

there are some colors that are, and just to be safe i changed one number

**Comment by no1crate** [comment]
Just deny the pr

**Comment by kurmachu** [comment]
I'm pretty sure you can close your own PR.

**Pull request closed without merging**
