### PR TITLE
Added Terminal theme.

### PR DESCRIPTION
**Pull request by donut28**
The terminal theme is under the dark theme category. Just checking everything right now.

### CODE REVIEW

**Comment by donut28** [comment]
Seems to be accessible, all the checks passed.

**Review by kurmachu — COMMENTED** [review]
Not 100% sure if you care, given the nature of the theme, but there is actually an accessibility warning.
image
I'm going to hold off on merging for now, until you either fix or confirm that you don't care.

**Comment by donut28** [comment]
Should pass those checks now.

**Review by kurmachu — APPROVED** [review]
Looks good!

**Pull request merged**
