### PR TITLE
Adding my theme, Darkest.

### PR DESCRIPTION
**Pull request by DotEXEGaming**

### CODE REVIEW

**Review by kurmachu — CHANGES_REQUESTED** [review]
image

Sorry for the delay.

**Comment by kurmachu** [comment]
Are you still working on this?

**Comment by DotEXEGaming** [comment]
My apologies for forgetting about it. Yes, I am. I will recheck it in the coming days and resend it here.

**Comment by kurmachu** [comment]
Don't worry! I just needed confirmation. There's no time limit as long as you respond.

**Comment by kurmachu** [comment]
Are you still working on this?

**Comment by DotEXEGaming** [comment]
I am yes, I will make the fix for the lini text when I get home today.

**Comment by DotEXEGaming** [comment]
I have changed the colours now, check please.

**Review by kurmachu — APPROVED** [review]

**Pull request merged**
