### PR TITLE
Nightowl and Contrast updated

### PR DESCRIPTION
**Pull request by roxwize**
I told you they'd be back. Let me know if I missed a new feature as finding what differed between the old Nightowl and the new Arithm was kind of tedious.

### CODE REVIEW

**Review by kurmachu — CHANGES_REQUESTED** [review]
Sorry for the delay, I've been quite busy.

image
image

---------------------------------------
✅ No other contrast or coverage issues found.

**Comment by thekifake** [comment]
Hullo, sorry for the wait. I'll fix this right now.

**Comment by kurmachu** [comment]
Are you still working on this?

**Comment by thekifake** [comment]
Hi. Sorry I kind of lied. School's been messing with my schedule; I'll be free on the weekends, so expect the changes to be added by then

**Comment by kurmachu** [comment]
Do not worry about the time, I just need occasional confirmation that this hasn't been abandoned, even if no progress has been made. School is hard and you don't control your schedule. I wish you the best in your endeavors and I wouldn't want you to prioritize this over something more important.

Get this done when you feel like it! Sorry for the trouble.

**Comment by kurmachu** [comment]
Due to technicalities, we are no longer accepting contributions at this time.

**Pull request closed without merging**
