### PR TITLE
New blue theme

### PR DESCRIPTION
**Pull request by donut28**
I did a nice blue theme. I don't know how to test it, so I'm not sure if it looks good, but it should look alright.
Let me know if I've missed something. Feel free to edit it also.

### CODE REVIEW

**Review by kurmachu — CHANGES_REQUESTED** [review]
I like the idea, but you need to do more than just change the background. You can preview themes online by simply editing css (using override files for persistence if you're fancy), or wait for me to finish writing the steps as to running the site locally.

I'm sadly required to reject on the grounds of accessibility. 
image

**Comment by donut28** [comment]
I think I have solved the link problems. I have tried to see the changes I have made so I can make sure its good but I can't seem to preview them. Hopefully this works.

**Comment by donut28** [comment]
Update: I just viewed it and the icons aren't looking good. Working on it now.

**Comment by kurmachu** [comment]
I've added a readme to the site with instructions to build the site, if you want an easier local preview.

**Comment by donut28** [comment]
It's looking way better than it was before. Is the accessibility good?

image

**Review by kurmachu — CHANGES_REQUESTED** [review]
Accessibility looks good! 
But, please rename **colours** to **colors**, in keeping with the american spelling style of the docs.

**Comment by donut28** [comment]
Alright, renamed the folder to colors. Should be all good now.

**Review by kurmachu — APPROVED** [review]

**Pull request merged**
