### PR TITLE
Hi-contrast theme

### PR DESCRIPTION
**Pull request by thekifake**
It's a theme for your eyes. Everything meets AAA standards, but if I missed anything let me know.

Theme

The two extra commits are GitHub's fault. If you go to changed files you'll see they don't actually change anything.

### CODE REVIEW

**Review by kurmachu — APPROVED** [review]
Looks good! If you'd like, you can move your theme to a specific "Accessible" category. I'll wait for your response as to if you'd like to do that before merging.

**Comment by kurmachu** [comment]
As of #17 we now have an "Accessible" category, so this would make sense. I'll wait for you to move the theme or confirm you'd like it moved.

Of course, you may choose to not move the theme to the "accessible" category. In that case, simply give me the go-ahead to merge everything as-is.

**Comment by thekifake** [comment]
Alright, good to go

**Review by donut28 — APPROVED** [review]
### ** _y e s_**

**Pull request merged**
